const test=require('node:test'),assert=require('node:assert/strict');
const express=require('express'),mongoose=require('mongoose');
const {toInputRows}=require('../utils/fuelConversion');
test('all five APIs persist formula metadata with recalculated rows and isolate months',async()=>{
 const configs=[['wider','wider','WiderData','lng'],['utility','utility','UtilityData','lngLpg'],['hsu','hsu','HsuData','lpg'],['narrow-flat','narrowFlat','NarrowFlatData','lpg'],['narrow-tube','narrowTube','NarrowTubeData','lpg']];
 const app=express();app.use(express.json());const restores=[];
 for(const [plant,file,model] of configs){app.use('/api/'+plant,require('../routes/'+file+'Routes'));const M=mongoose.model(model),oldFind=M.findOne,oldUpdate=M.findOneAndUpdate;const docs=new Map([['2026-08',{monthYear:'2026-08',rows:[],totals:{totalConsumption:1234}}]]);M.findOne=async query=>docs.get(query.monthYear)||null;M.findOneAndUpdate=async(query,update)=>{const document=new M(update);await document.validate();const result=document.toObject();docs.set(query.monthYear,result);return result;};restores.push(()=>{M.findOne=oldFind;M.findOneAndUpdate=oldUpdate;});}
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));const base=`http://127.0.0.1:${server.address().port}/api`;
 try{for(const [plant,,,key] of configs){const formula={ELECTRICITY:1,LNG:15,LPG:12,HSD:4};const body={monthYear:'2026-09',inputBasis:'quantity-v1',formula,rows:[{equipment:'Example',electricity:1000,[key]:10,hsd:5,production:10,enpiUnit:'kWh/MT',fuelType:'LNG'}]};const post=async data=>{const response=await fetch(`${base}/${plant}/save`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});assert.equal(response.status,200);return response.json();};await post(body);const loaded=await (await fetch(`${base}/${plant}?month=2026-09`)).json();assert.deepEqual(loaded.formula,formula);assert.equal(loaded.rows[0].totalConsumption,1170);assert.equal(loaded.rows[0].fuelFactor,15);const again=await post({...body,rows:toInputRows(plant,'2026-09',loaded.rows)});assert.equal(again.data.totals.totalConsumption,1170);const august=await(await fetch(`${base}/${plant}?month=2026-08`)).json();assert.equal(august.totals.totalConsumption,1234);}}
 finally{restores.forEach(f=>f());server.closeAllConnections();await new Promise(r=>server.close(r));}
});
