import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {Bar,BarChart,CartesianGrid,Cell,ComposedChart,Legend,Line,LineChart,Pie,PieChart,ReferenceArea,ReferenceLine,Tooltip,XAxis,YAxis} from 'recharts';
import ExpandableChart from '../components/ExpandableChart';
import {API_BASE_URL,apiFetch} from '../config/api';
import {initialRows,monthLabels,plants,summarize} from '../utils/seu';
import './seu.css';
const equipmentNames={7:'6HI',8:'CGL',9:'CCL',10:'COMPRESSOR',11:'Pump house',12:'Boiler(LPG)',13:'ARP(LNG)',14:'N2 Plant',15:'MEE PLANT(LPG)',16:'CRM',17:'CGL',18:'CCL',19:'BOILER',20:'ZY-120 MILL',21:'FD-200 MILL',22:'ZY-500 MILL+1800KWHF',23:'OLIMPIA MILL',24:'PUMP HOUSE',25:'GMT-1',26:'GMT-2',27:'GMT-3',28:'GMT-4',29:'ZY-63',30:'PUMP HOUSE',31:'COMPRESSOR'};
const colors=['#7c3aed','#0d9488','#db2777','#ea580c','#2563eb','#0891b2','#65a30d','#9333ea','#e11d48','#ca8a04','#0284c7','#059669'];
const fmt=v=>v==null?'—':v.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const signed=v=>v==null?'—':`${v>0?'+':''}${fmt(v)}%`;
function Chart({title,children,height=340}){return <section className="seu-chart"><h2>{title}</h2><div style={{height}}><ExpandableChart preservePieHole>{children}</ExpandableChart></div></section>;}
export default function SeuPage(){
const {plant}=useParams();const [year,setYear]=useState(2026),[filter,setFilter]=useState('all'),[selected,setSelected]=useState(''),[start,setStart]=useState(0),[end,setEnd]=useState(11),[records,setRecords]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0),[edit,setEdit]=useState(null),[saving,setSaving]=useState(false),[notice,setNotice]=useState('');
useEffect(()=>{const c=new AbortController();setLoading(true);setError('');setRecords([]);setEdit(null);setNotice('');apiFetch(`${API_BASE_URL}/api/seu/${year}`,{signal:c.signal}).then(async r=>{if(!r.ok)throw Error('Saved SEU records unavailable. Reference data shown; retry before editing.');const d=await r.json();if(!Array.isArray(d.records))throw Error('Invalid SEU response');return d;}).then(d=>{if(!c.signal.aborted)setRecords(d.records);}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[year,retry,plant]);
if(!plants[plant])return <main><h1>Unknown plant</h1><Link to="/">Home</Link></main>;
const rows=initialRows(year).map(r=>{const s=records.find(x=>x.id===r.id);return {...r,...s,name:r.name,plant:r.plant,revision:s?.revision||0};}).filter(r=>plant==='abpl'?(filter==='all'||filter===r.plant):r.plant===plant);
const visible=selected?rows.filter(r=>r.id===selected):rows, active=visible[0],months=monthLabels(year),stats=visible.map(r=>({...r,...summarize(r,start,end)}));
const data=active?months.map((month,i)=>({month,actual:active.values[i],baseline:active.baseline,target:active.target})).slice(start,end+1):[];
const achieved=stats.filter(r=>r.deviation!==null&&r.deviation>=0).length,lagging=stats.filter(r=>r.deviation!==null&&r.deviation<0).length;
const pie=[{name:'Target achieved',value:achieved,color:'#059669'},{name:'Lagging',value:lagging,color:'#e11d48'},{name:'No comparison',value:stats.length-achieved-lagging,color:'#94a3b8'}].filter(r=>r.value);
async function save(e){e.preventDefault();setSaving(true);setNotice('');try{const r=await apiFetch(`${API_BASE_URL}/api/seu/${year}/${edit.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(edit)});const d=await r.json();if(!r.ok)throw Error(d.error||'Save failed');setRecords(old=>[...old.filter(x=>x.id!==edit.id),d.record]);setEdit(null);setNotice('SEU record saved.');}catch(e){setNotice(e.message);}finally{setSaving(false);}}
return <main className={`seu-page seu-${plant} enpi-targets`}><header className="seu-hero"><div><Link to={`/${plant}`}>← Back to {plants[plant]}</Link><p>ENERGY PERFORMANCE REGISTER</p><h1>⚡ {plants[plant]} <span>SEU insights</span></h1><p>Significant Energy Uses · Baseline to target · April–March</p></div><strong>FY {year}–{String(year+1).slice(-2)}</strong></header>
<section className="seu-filters"><label>Financial year<select disabled={saving} value={year} onChange={e=>{setYear(+e.target.value);setSelected('');}}>{Array.from({length:6},(_,i)=>2025+i).map(y=><option key={y} value={y}>{y}–{String(y+1).slice(-2)}</option>)}</select></label>{plant==='abpl'&&<label>Plant<select value={filter} onChange={e=>{setFilter(e.target.value);setSelected('');}}><option value="all">All plants</option>{Object.entries(plants).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>}<label>Equipment<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">All SEUs</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>From<select value={start} onChange={e=>{setStart(+e.target.value);setEnd(Math.max(end,+e.target.value));}}>{months.map((m,i)=><option key={m} value={i}>{m}</option>)}</select></label><label>To<select value={end} onChange={e=>setEnd(+e.target.value)}>{months.map((m,i)=>i>=start&&<option key={m} value={i}>{m}</option>)}</select></label></section>
<p className="seu-note">Apr–Aug 2026 uses your supplied SEU figures. Update monthly values through Edit; this register is separate from energy inputs. Missing months are excluded from averages. Positive deviation means better performance. ±3% is tolerance, not statistical standard deviation. Olampia’s unit was not supplied.</p>{loading&&<p role="status">Loading saved records…</p>}{error&&<p className="seu-alert" role="alert">{error} <button onClick={()=>setRetry(x=>x+1)}>Retry</button></p>}{notice&&<p className="seu-alert" role="status">{notice}</p>}
<section className="seu-cards">{[['Total SEUs',stats.length],['Target achieved',achieved],['Lagging',lagging],['Outside tolerance',stats.filter(r=>r.outside).length]].map(([label,value],i)=><article key={label} style={{background:['linear-gradient(120deg,#4f46e5,#8b5cf6)','linear-gradient(120deg,#047857,#14b8a6)','linear-gradient(120deg,#be123c,#fb7185)','linear-gradient(120deg,#b45309,#f59e0b)'][i]}}><span>{label}</span><strong>{value}</strong></article>)}</section>
<section className="seu-register"><h2>SEU performance register</h2><p>Click an equipment name to open its energy history. Use the Equipment filter above for SEU baseline/target charts. Energy history uses saved plant inputs, separate from this SEU register.</p><div className="seu-scroll"><table><thead><tr>{['No.','Facility / Process / Equipment','Indicator','Performance','Baseline','Target',...months.slice(start,end+1),'Tolerance','Deviation','Average achieved','Months','Action'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{stats.map(r=><tr key={r.id}><td>{r.id}</td><th><>{equipmentNames[r.id]?<Link className="seu-name" to={`/equipment/${r.plant}?${new URLSearchParams({equipment:equipmentNames[r.id],month:`${year+(end>=9?1:0)}-${String((end+3)%12+1).padStart(2,'0')}`,range:'12'})}`}>{r.name} ↗</Link>:<button className="seu-name" onClick={()=>setSelected(r.id)}>{r.name}</button>}</><small>{plants[r.plant]} · {r.revision?'Saved':'Reference'}</small></th><td>{r.unit||'Not supplied'}</td><td><span className={`seu-badge ${r.deviation===null?'neutral':r.deviation<0?'bad':'good'}`}>{r.deviation===null?'—':r.deviation<0?'▼':'▲'} {r.status}</span></td><td>{fmt(r.baseline)}</td><td>{fmt(r.target)}</td>{r.values.slice(start,end+1).map((v,i)=>{const s=summarize({...r,values:[v]},0,0);return <td key={i} className={s.deviation===null?'':s.deviation<0?'negative':'positive'}>{fmt(v)}</td>;})}<td>{r.tolerance===null?'—':`±${r.tolerance}%`}</td><td className={r.deviation<0?'negative':'positive'}>{signed(r.deviation)}</td><td><b>{fmt(r.average)}</b></td><td>{r.count}/{end-start+1}</td><td><button disabled={loading||!!error||saving} onClick={()=>{setEdit({...r,values:[...r.values]});setNotice('');setTimeout(()=>document.getElementById('seu-editor')?.scrollIntoView({behavior:'smooth'}),0);}}>Edit</button>{r.remark&&<details><summary>Remarks</summary><p>{r.remark}</p></details>}</td></tr>)}</tbody></table></div></section>
{active&&<><h2>{active.name} <small>· {active.unit||'Unit not supplied'}</small></h2>{!selected&&<p>Monthly charts show the first visible SEU. Select an equipment above to change it.</p>}<section className="seu-charts"><Chart title="Monthly achieved EnPI"><ComposedChart data={data} margin={{top:25,right:20,left:15,bottom:10}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip/><Legend/><Bar dataKey="actual" name="Achieved" radius={[6,6,0,0]}>{data.map((r,i)=><Cell key={r.month} fill={colors[i%colors.length]}/>)}</Bar><Line dataKey="baseline" name="Baseline" stroke="#7c3aed" dot={false} strokeDasharray="5 5"/><Line dataKey="target" name="Target" stroke="#059669" dot={false}/></ComposedChart></Chart>
<Chart title="Trend & tolerance band"><LineChart data={data} margin={{top:25,right:20,left:15,bottom:10}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis domain={['auto','auto']}/><Tooltip/><Legend/>{active.target!==null&&active.tolerance!==null&&<ReferenceArea y1={active.target*(1-active.tolerance/100)} y2={active.target*(1+active.tolerance/100)} fill="#10b981" fillOpacity={.15} ifOverflow="extendDomain"/>}<Line dataKey="actual" name="Achieved" stroke="#db2777" strokeWidth={3} connectNulls={false}/><Line dataKey="target" name="Target" stroke="#059669" dot={false}/><Line dataKey="baseline" name="Baseline" stroke="#7c3aed" dot={false} strokeDasharray="5 5"/></LineChart></Chart>
<Chart title="Target deviation (%)" height={Math.max(340,stats.length*30)}><BarChart data={stats.filter(r=>r.deviation!==null)} layout="vertical" margin={{left:10,right:30,top:25,bottom:10}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number"/><YAxis type="category" dataKey="name" width={160} tick={{fontSize:11}} interval={0}/><Tooltip formatter={v=>signed(v)}/><ReferenceLine x={0}/><Bar dataKey="deviation" name="Better (+) / Behind (−)">{stats.filter(r=>r.deviation!==null).map(r=><Cell key={r.id} fill={r.deviation<0?'#e11d48':'#059669'}/>)}</Bar></BarChart></Chart><Chart title="SEUs meeting target"><PieChart><Tooltip/><Legend/><Pie data={pie} dataKey="value" nameKey="name" innerRadius={60} outerRadius={100} label>{pie.map(r=><Cell key={r.name} fill={r.color}/>)}</Pie></PieChart></Chart></section></>}
{edit&&<section id="seu-editor" className="seu-editor"><form onSubmit={save}><h2>Edit {edit.name} · FY {year}–{String(year+1).slice(-2)}</h2><p>Blank values stay missing. Saving updates this SEU register only.</p><fieldset disabled={saving}><div className="seu-edit-grid"><label>Indicator unit<input value={edit.unit} maxLength={40} onChange={e=>setEdit({...edit,unit:e.target.value})}/></label><label>Better when<select value={edit.direction} onChange={e=>setEdit({...edit,direction:e.target.value})}><option value="lower">Lower</option><option value="higher">Higher</option></select></label>{['baseline','target','tolerance'].map(k=><label key={k}>{k}<input type="number" min="0" step="any" value={edit[k]??''} onChange={e=>setEdit({...edit,[k]:e.target.value===''?null:+e.target.value})}/></label>)}{months.map((m,i)=><label key={m}>{m}<input type="number" min="0" step="any" value={edit.values[i]??''} onChange={e=>setEdit({...edit,values:edit.values.map((v,j)=>i===j?(e.target.value===''?null:+e.target.value):v)})}/></label>)}</div><label>Remarks<textarea maxLength={3000} value={edit.remark} onChange={e=>setEdit({...edit,remark:e.target.value})}/></label></fieldset><div className="seu-edit-actions"><button disabled={saving} type="submit">{saving?'Saving…':'Save SEU record'}</button><button disabled={saving} type="button" onClick={()=>setEdit(null)}>Cancel</button></div>{notice&&<p role="status">{notice}</p>}</form></section>}</main>;
}
