const esc=value=>String(value??'N/A').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function printChatReport(message) {
 const popup=window.open('','_blank');
 if(!popup)throw Error('Allow pop-ups to open the report, then choose Save as PDF.');
 const chartNode=document.getElementById(`chat-answer-${message.id}`)?.querySelector('.chat-chart');
 const svg=chartNode?.querySelector('svg.recharts-surface')?.outerHTML||'';
 const chart=svg?`<section><h2>${esc(chartNode.querySelector('h3')?.textContent||'Selected chart')}</h2><div style="width:100%;overflow:hidden">${svg}</div><p>Selected chart view. Complete values are in the tables below.</p></section>`:'';
 const tables=(message.tables||[]).map(t=>`<section><h2>${esc(t.title)}</h2><table><thead><tr>${t.columns.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${t.rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></section>`).join('');
 popup.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>ABPL Energy Review</title><style>@page{size:A4 landscape;margin:14mm}body{font:13px system-ui,sans-serif;color:#20314c;margin:24px}header{background:#172d50;color:white;border-left:8px solid #14b8a6;padding:25px;border-radius:16px}h1{margin:0 0 8px}h2{color:#1d4ed8;font-size:17px}p{white-space:pre-wrap;line-height:1.7;overflow-wrap:anywhere}section{margin:25px 0}table{border-collapse:collapse;width:100%;font-size:10px;table-layout:fixed}th{background:#203b64;color:white}td,th{padding:9px;border:1px solid #dbe4ef;text-align:left;overflow-wrap:anywhere}tr:nth-child(even){background:#edf5ff}tr{break-inside:avoid}thead{display:table-header-group}.notice{background:#ecfdf5;border-left:4px solid #0d9488;padding:12px}button{padding:12px;background:#2563eb;color:white;border:0;border-radius:8px;margin-bottom:15px}a{color:#164fa0}svg{max-width:100%;height:auto}@media print{button{display:none}body{margin:0}*{print-color-adjust:exact;-webkit-print-color-adjust:exact}}</style></head><body><button onclick="window.print()">Print / Save as PDF</button><header><h1>ABPL · Energy Review</h1><div>${esc(message.scope.plants.join(', '))} · ${esc(message.scope.from)} to ${esc(message.scope.to)}</div><div>Generated: ${esc(message.generatedAt||new Date().toISOString())}</div></header><section><h2>Question</h2><p>${esc(message.question)}</p><h2>Answer</h2><p>${esc(message.answer)}</p></section><p class="notice">${esc(message.notice||'Read-only report based on selected saved records.')}${message.coverage?` · Missing plant-month records: ${esc(message.coverage.missing?.length??0)}`:''}</p>${chart}${tables}<section><h2>Source references</h2>${(message.sources||[]).map(s=>`<p>${esc(s.id)} · ${esc(s.label)}<br>${esc(new URL(s.url,window.location.origin).href)}</p>`).join('')}</section><footer>Review coverage, units and source records before drawing conclusions. Mixed production units must not be compared as tonnes.</footer></body></html>`);
 popup.document.close();
}
