import {regular,bold} from './seuReportFonts.js';
import {jsPDF} from 'jspdf';
import {formatNumber} from './seuComparison.js';
const P={ink:[25,39,66],muted:[91,107,131],purple:[109,40,217],cyan:[8,145,178],green:[4,120,87],pink:[190,24,93],light:[245,247,253]};
const clean=s=>String(s??'').replace(/³/g,'3').replace(/²/g,'2').replace(/[–—]/g,'-').replace(/[^\x20-\x7e]/g,'');
const periodAverage=(row,start,end)=>{const values=(row?.values||[]).slice(start,end+1).filter(n=>typeof n==='number'&&Number.isFinite(n));return values.length?values.reduce((a,b)=>a+b,0)/values.length:null;};
const fmt=n=>typeof n==='number'&&Number.isFinite(n)?formatNumber(n):'N/A';
export function createSeuReport({comparisons,year,plantName,start,end,reference=false,generatedAt=new Date()}){
 const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4',compress:true});
 doc.addFileToVFS('Report-Regular.ttf',regular);doc.addFont('Report-Regular.ttf','Report','normal');doc.addFileToVFS('Report-Bold.ttf',bold);doc.addFont('Report-Bold.ttf','Report','bold');
 doc.setProperties({title:`${plantName} SEU performance | 2025-26 vs 2026-27`,author:'Apollo Building Product Limited',subject:'Monthly EnPI register and matched-period comparison'});
 const W=297,H=210,M=16,CW=W-2*M;
 function text(value,x,y,size=10,color=P.ink,bold=false,options={}){doc.setTextColor(...color);doc.setFont('Report',bold?'bold':'normal');doc.setFontSize(size);doc.text(clean(value),x,y,options);}
 function wrapped(value,x,y,width,size=9,color=P.muted){doc.setFont('Report','normal');doc.setFontSize(size);const lines=doc.splitTextToSize(clean(value),width);doc.setTextColor(...color);doc.text(lines,x,y);return lines.length*size*.4;}
 function top(kicker,title){doc.setFillColor(...P.ink);doc.rect(0,0,W,32,'F');doc.setFillColor(...P.purple);doc.rect(0,32,W/2,2,'F');doc.setFillColor(...P.cyan);doc.rect(W/2,32,W/2,2,'F');text(kicker.toUpperCase(),M,11,8,[190,210,236],true);text(title,M,24,18,[255,255,255],true);text('EMS / ENERGY INTELLIGENCE',W-M,11,8,[190,210,236],false,{align:'right'});}
 function card(x,y,w,label,value,color){doc.setFillColor(...color);doc.roundedRect(x,y,w,23,3,3,'F');text(label,x+5,y+7,8,[235,240,255]);text(value,x+5,y+17,16,[255,255,255],true);}
 const selectedMonths=['Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar'].slice(start,end+1).join(', ');
 const comparable=comparisons.filter(c=>c.improvement!==null);
 top('Apollo Building Product Limited',`${plantName} | SEU performance report`);
 text('FINANCIAL YEAR COMPARISON',M,45,11,P.purple,true);text('2025-26  /  2026-27',M,59,25,P.ink,true);
 wrapped(`Register selection: FY ${year}-${String(year+1).slice(-2)} | Months: ${selectedMonths}. Generated ${generatedAt.toISOString().slice(0,10)} (UTC).`,M,69,CW);
 [['SELECTED SEUs',comparisons.length,P.purple],['COMPARABLE',comparable.length,P.cyan],['IMPROVED',comparable.filter(c=>c.improvement>0).length,P.green],['WORSENED',comparable.filter(c=>c.improvement<0).length,P.pink]].forEach(([label,value,col],i)=>card(M+i*67,81,64,label,String(value),col));
 text('How to read this report',M,118,13,P.ink,true);
 const notes=[
 'Comparison uses only months recorded in BOTH years, with matching indicator units. Missing entries are N/A; recorded zeros remain zero.',
 'Change % = (2026-27 average - 2025-26 average) / 2025-26 average x 100. A zero previous average has no percentage change.',
 'Lower-is-better and higher-is-better indicators are evaluated separately. Different equipment identities and incompatible units are not compared.',
 'Supplied 2025-26 annual averages and deviations are preserved. They can differ from arithmetic monthly averages; no production-weighted EnPI is inferred.',
 'Source: user-supplied FY 2025-26 and FY 2026-27 SEU registers, plus available saved SEU edits. SEU figures are separate from plant consumption inputs.',
 reference?'REFERENCE SNAPSHOT: saved updates could not be verified for one or both years. This is not a confirmed current database report.':'Saved updates checked for both years. Unchanged entries retain their supplied reference values.'
 ];let y=128;for(const note of notes)y+=wrapped(note,M,y,CW,9,reference&&note.startsWith('REFERENCE')?P.pink:P.muted)+5;
 for(let offset=0;offset<comparisons.length;offset+=11){doc.addPage();top('Matched-period results',`${plantName} | comparison summary`);text(`Common recorded months only | Rows ${offset+1}-${Math.min(offset+11,comparisons.length)} of ${comparisons.length}`,M,43,9,P.muted);
 const xs=[M,M+76,M+112,M+150,M+188,M+212];const widths=[76,36,38,38,24,53];doc.setFillColor(...P.purple);doc.rect(M,49,CW,10,'F');['SEU / Equipment','Unit','2025-26 avg','2026-27 avg','Months','Change / Status'].forEach((h,i)=>text(h,xs[i]+3,55.5,8,[255,255,255],true));
 comparisons.slice(offset,offset+11).forEach((c,i)=>{const yy=59+i*11.5;doc.setFillColor(...(i%2?[237,242,251]:[249,250,254]));doc.rect(M,yy,CW,11.5,'F');wrapped(c.name,xs[0]+3,yy+4.5,widths[0]-6,8,P.ink);text(c.unitMatches?c.current.unit:'See detail',xs[1]+3,yy+6,8);text(fmt(c.previousAverage),xs[2]+3,yy+6,9);text(fmt(c.currentAverage),xs[3]+3,yy+6,9);text(c.paired.length,xs[4]+3,yy+6,9);wrapped(c.reason||(fmt(c.change)+'% / '+(c.improvement>0?'Improved':c.improvement<0?'Worsened':'Unchanged')),xs[5]+3,yy+4.5,widths[5]-6,8,c.improvement<0?P.pink:P.green);});}
 function chart(points,series,x,y,w,h,title){doc.setFillColor(...P.light);doc.roundedRect(x,y,w,h,3,3,'F');text(title,x+5,y+7,9,P.ink,true);series.forEach((s,i)=>{doc.setFillColor(...s.color);doc.rect(x+6+i*57,y+11,3,2,'F');text(s.label,x+11+i*57,y+13,7,P.muted);});const px=x+16,py=y+20,pw=w-23,ph=h-31;const values=points.flatMap(p=>series.map(s=>p[s.key])).filter(v=>typeof v==='number'&&Number.isFinite(v));if(!values.length){text('No recorded values in selected months',x+7,y+h/2,9,P.muted);return;}
 const max=Math.max(...values,0)*1.12||1;for(let i=0;i<=3;i++){const yy=py+ph-i/3*ph;doc.setDrawColor(215,223,237);doc.setLineWidth(.15);doc.line(px,yy,px+pw,yy);text(max*i/3>=10000?(max*i/3000).toFixed(0)+'k':(max*i/3).toFixed(max<10?2:0),px-2,yy+1.2,6,P.muted,false,{align:'right'});}const step=pw/points.length;points.forEach((p,i)=>text(p.month,px+step*(i+.5),py+ph+5,6,P.muted,false,{align:'center'}));
 for(const [si,s] of series.entries()){let previous=null;points.forEach((p,i)=>{const v=p[s.key];if(typeof v!=='number'||!Number.isFinite(v)){previous=null;return;}const xx=px+step*(i+.5),yy=py+ph-v/max*ph;doc.setDrawColor(...s.color);doc.setFillColor(...s.color);if(title.includes('Bar')){const bw=step*.65/series.length;doc.rect(xx-step*.325+si*bw,yy,bw*.9,Math.max(v/max*ph,.25),'F');}else{doc.setLineWidth(.6);if(previous)doc.line(previous.x,previous.y,xx,yy);doc.circle(xx,yy,.8,'F');previous={x:xx,y:yy};}});}}
 for(const c of comparisons){doc.addPage();top(`${plantName} | equipment detail`,c.name);const prev=c.previous,cur=c.current;text(`2025-26: ${prev?.unit||'Not listed'} | Baseline ${fmt(prev?.baseline)} | Target ${fmt(prev?.target)} | Selected-period average ${fmt(periodAverage(prev,start,end))}`,M,42,8,P.purple,true);text(`2026-27: ${cur?.unit||'Not listed'} | Baseline ${fmt(cur?.baseline)} | Target ${fmt(cur?.target)} | Selected-period average ${fmt(periodAverage(cur,start,end))}`,M,48,8,P.cyan,true);
 [['2025-26 MATCHED AVG',fmt(c.previousAverage),P.purple],['2026-27 MATCHED AVG',fmt(c.currentAverage),P.cyan],['YEAR CHANGE',c.change===null?'N/A':fmt(c.change)+'%',P.pink],['COMMON MONTHS',String(c.paired.length),P.green]].forEach(([label,value,col],i)=>card(M+i*67,54,64,label,value,col));
 const series=[{key:'previous',label:'2025-26',color:P.purple},{key:'current',label:'2026-27',color:P.cyan}];if(c.unitMatches){chart(c.points,series,M,83,129,57,'Bar comparison | '+cur.unit);chart(c.points,series,M+136,83,129,57,'Line trends | '+cur.unit);}else{chart(c.points,[series[0]],M,83,129,57,'Bar | 2025-26 | '+(prev?.unit||'Not listed'));chart(c.points,[series[1]],M+136,83,129,57,'Line | 2026-27 | '+(cur?.unit||'Not listed'));}
 const col=CW/(c.points.length+1);doc.setFillColor(...P.ink);doc.rect(M,146,CW,8,'F');text('EnPI',M+2,151.5,7,[255,255,255],true);c.points.forEach((p,i)=>text(p.month,M+col*(i+1.5),151.5,7,[255,255,255],true,{align:'center'}));for(const [i,key] of ['previous','current'].entries()){const yy=154+i*8;doc.setFillColor(...(i?[225,247,250]:[240,231,254]));doc.rect(M,yy,CW,8,'F');text(i?'2026-27':'2025-26',M+2,yy+5.3,7,P.ink,true);c.points.forEach((p,j)=>text(fmt(p[key]),M+col*(j+1.5),yy+5.3,7,P.ink,false,{align:'center'}));}
 let yy=177;if(c.reason)yy+=wrapped('Comparison note: '+c.reason+'. Each chart retains its stated year and unit.',M,yy,CW,8,P.pink)+2;if(prev&&prev.sourceAverage!=null)yy+=wrapped(`2025-26 supplied ANNUAL figures: average ${fmt(prev.sourceAverage)}; deviation ${fmt(prev.sourceDeviation)}%. Original serial ${prev.sourceSerial}. These are source figures, not recalculated matched-period results.`,M,yy,CW,8)+2;wrapped(`Status: 2025-26 ${prev?(prev.revision?'saved revision '+prev.revision:'supplied reference'):'not listed'}; 2026-27 ${cur?(cur.revision?'saved revision '+cur.revision:'supplied reference'):'not listed'}. N/A means missing. ${reference?'REFERENCE SNAPSHOT - saved updates not fully verified.':''}`,M,yy,CW,7);}
 const total=doc.getNumberOfPages();for(let page=1;page<=total;page++){doc.setPage(page);doc.setDrawColor(217,225,238);doc.line(M,H-12,W-M,H-12);text(reference?'EMS | REFERENCE SNAPSHOT':'EMS | SEU annual performance',M,H-7,7,P.muted);text(`${page} / ${total}`,W-M,H-7,8,P.muted,false,{align:'right'});}return doc;
}
